<a href="https://colab.research.google.com/github/parth1614/Machine_Learning/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from google.colab import files

In [4]:
uploaded = files.upload()

Saving 50_AdAgency.csv to 50_AdAgency.csv


In [6]:
dataframe = pd.read_csv("50_AdAgency.csv")

In [7]:
dataframe

Print Media Expenses  Social Media Expenses  ...        City     Profit
0              165349.20              136897.80  ...      Mumbai  192261.83
1              162597.70              151377.59  ...  Chandigarh  191792.06
2              153441.51              101145.55  ...       Delhi  191050.39
3              144372.41              118671.85  ...      Mumbai  182901.99
4              142107.34               91391.77  ...       Delhi  166187.94
5              131876.90               99814.71  ...      Mumbai  156991.12
6              134615.46              147198.87  ...  Chandigarh  156122.51
7              130298.13              145530.06  ...       Delhi  155752.60
8              120542.52              148718.95  ...      Mumbai  152211.77
9              123334.88              108679.17  ...  Chandigarh  149759.96
10             101913.08              110594.11  ...       Delhi  146121.95
11             100671.96               91790.61  ...  Chandigarh  144259.40
12              93863.75              127320.38  ...       Delhi  141585.52
13              91992.39              135495.07  ...  Chandigarh  134307.35
14             119943.24              156547.42  ...       Delhi  132602.65
15             114523.61              122616.84  ...      Mumbai  129917.04
16              78013.11              121597.55  ...  Chandigarh  126992.93
17              94657.16              145077.58  ...      Mumbai  125370.37
18              91749.16              114175.79  ...       Delhi  124266.90
19              86419.70              153514.11  ...      Mumbai  122776.86
20              76253.86              113867.30  ...  Chandigarh  118474.03
21              78389.47              153773.43  ...      Mumbai  111313.02
22              73994.56              122782.75  ...       Delhi  110352.25
23              67532.53              105751.03  ...       Delhi  108733.99
24              77044.01               99281.34  ...      Mumbai  108552.04
25              64664.71              139553.16  ...  Chandigarh  107404.34
26              75328.87              144135.98  ...       Delhi  105733.54
27              72107.60              127864.55  ...      Mumbai  105008.31
28              66051.52              182645.56  ...       Delhi  103282.38
29              65605.48              153032.06  ...      Mumbai  101004.64
30              61994.48              115641.28  ...       Delhi   99937.59
31              61136.38              152701.92  ...      Mumbai   97483.56
32              63408.86              129219.61  ...  Chandigarh   97427.84
33              55493.95              103057.49  ...       Delhi   96778.92
34              46426.07              157693.92  ...  Chandigarh   96712.80
35              46014.02               85047.44  ...      Mumbai   96479.51
36              28663.76              127056.21  ...       Delhi   90708.19
37              44069.95               51283.14  ...  Chandigarh   89949.14
38              20229.59               65947.93  ...      Mumbai   81229.06
39              38558.51               82982.09  ...  Chandigarh   81005.76
40              28754.33              118546.05  ...  Chandigarh   78239.91
41              27892.92               84710.77  ...       Delhi   77798.83
42              23640.93               96189.63  ...  Chandigarh   71498.49
43              15505.73              127382.30  ...      Mumbai   69758.98
44              22177.74              154806.14  ...  Chandigarh   65200.33
45               1000.23              124153.04  ...      Mumbai   64926.08
46               1315.46              115816.21  ...       Delhi   49490.75
47                  0.00              135426.92  ...  Chandigarh   42559.73
48                542.05               51743.15  ...      Mumbai   35673.41
49                  0.00              116983.80  ...  Chandigarh   14681.40

[50 rows x 5 columns]

In [13]:
X = dataframe.iloc[:, :-1].values
y = dataframe.iloc[:, 4].values

In [11]:
X

array([[165349.2, 136897.8, 471784.1, 'Mumbai'],
       [162597.7, 151377.59, 443898.53, 'Chandigarh'],
       [153441.51, 101145.55, 407934.54, 'Delhi'],
       [144372.41, 118671.85, 383199.62, 'Mumbai'],
       [142107.34, 91391.77, 366168.42, 'Delhi'],
       [131876.9, 99814.71, 362861.36, 'Mumbai'],
       [134615.46, 147198.87, 127716.82, 'Chandigarh'],
       [130298.13, 145530.06, 323876.68, 'Delhi'],
       [120542.52, 148718.95, 311613.29, 'Mumbai'],
       [123334.88, 108679.17, 304981.62, 'Chandigarh'],
       [101913.08, 110594.11, 229160.95, 'Delhi'],
       [100671.96, 91790.61, 249744.55, 'Chandigarh'],
       [93863.75, 127320.38, 249839.44, 'Delhi'],
       [91992.39, 135495.07, 252664.93, 'Chandigarh'],
       [119943.24, 156547.42, 256512.92, 'Delhi'],
       [114523.61, 122616.84, 261776.23, 'Mumbai'],
       [78013.11, 121597.55, 264346.06, 'Chandigarh'],
       [94657.16, 145077.58, 282574.31, 'Mumbai'],
       [91749.16, 114175.79, 294919.57, 'Delhi'],
       [

In [14]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [15]:
from sklearn.preprocessing import LabelEncoder

In [17]:
labelencoder = LabelEncoder()
X[:,3] = labelencoder.fit_transform(X[:,3]) ##preprocessing because the values in city column are nominal values, i.e. they can't be meaningfully ranked

In [18]:
X

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [19]:
from sklearn.preprocessing import OneHotEncoder 

In [25]:
## to convert the labeled values of cities into dummy variables
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [3])], remainder='passthrough') ## column number 3 has the dummy variables
X=np.array(columnTransformer.fit_transform(X),dtype=np.str)


In [26]:
X

array([['0.0', '0.0', '1.0', '165349.2', '136897.8', '471784.1'],
       ['1.0', '0.0', '0.0', '162597.7', '151377.59', '443898.53'],
       ['0.0', '1.0', '0.0', '153441.51', '101145.55', '407934.54'],
       ['0.0', '0.0', '1.0', '144372.41', '118671.85', '383199.62'],
       ['0.0', '1.0', '0.0', '142107.34', '91391.77', '366168.42'],
       ['0.0', '0.0', '1.0', '131876.9', '99814.71', '362861.36'],
       ['1.0', '0.0', '0.0', '134615.46', '147198.87', '127716.82'],
       ['0.0', '1.0', '0.0', '130298.13', '145530.06', '323876.68'],
       ['0.0', '0.0', '1.0', '120542.52', '148718.95', '311613.29'],
       ['1.0', '0.0', '0.0', '123334.88', '108679.17', '304981.62'],
       ['0.0', '1.0', '0.0', '101913.08', '110594.11', '229160.95'],
       ['1.0', '0.0', '0.0', '100671.96', '91790.61', '249744.55'],
       ['0.0', '1.0', '0.0', '93863.75', '127320.38', '249839.44'],
       ['1.0', '0.0', '0.0', '91992.39', '135495.07', '252664.93'],
       ['0.0', '1.0', '0.0', '119943.24', '1

In [27]:
# We can always work with (n-1) dummy variables, so we'll code the dummy variable trap
X = X[:,1:]

In [28]:
X

array([['0.0', '1.0', '165349.2', '136897.8', '471784.1'],
       ['0.0', '0.0', '162597.7', '151377.59', '443898.53'],
       ['1.0', '0.0', '153441.51', '101145.55', '407934.54'],
       ['0.0', '1.0', '144372.41', '118671.85', '383199.62'],
       ['1.0', '0.0', '142107.34', '91391.77', '366168.42'],
       ['0.0', '1.0', '131876.9', '99814.71', '362861.36'],
       ['0.0', '0.0', '134615.46', '147198.87', '127716.82'],
       ['1.0', '0.0', '130298.13', '145530.06', '323876.68'],
       ['0.0', '1.0', '120542.52', '148718.95', '311613.29'],
       ['0.0', '0.0', '123334.88', '108679.17', '304981.62'],
       ['1.0', '0.0', '101913.08', '110594.11', '229160.95'],
       ['0.0', '0.0', '100671.96', '91790.61', '249744.55'],
       ['1.0', '0.0', '93863.75', '127320.38', '249839.44'],
       ['0.0', '0.0', '91992.39', '135495.07', '252664.93'],
       ['1.0', '0.0', '119943.24', '156547.42', '256512.92'],
       ['0.0', '1.0', '114523.61', '122616.84', '261776.23'],
       ['0.0', '0.

In [29]:
# splitting the datset into training and testing dataset
from sklearn.model_selection import train_test_split


In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [34]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:755: FutureWarning: Beginning in version 0.22, arrays of bytes/strings will be converted to decimal numbers if dtype='numeric'. It is recommended that you convert the array to a float dtype before using it in scikit-learn, for example by using your_array = your_array.astype(np.float64).
  estimator=estimator)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
X_test = np.asarray(X_test, dtype='float64')

In [42]:
X_test

array([[1.0000000e+00, 0.0000000e+00, 6.6051520e+04, 1.8264556e+05,
        1.1814820e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0067196e+05, 9.1790610e+04,
        2.4974455e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0191308e+05, 1.1059411e+05,
        2.2916095e+05],
       [1.0000000e+00, 0.0000000e+00, 2.7892920e+04, 8.4710770e+04,
        1.6447071e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       [0.0000000e+00, 1.0000000e+00, 7.2107600e+04, 1.2786455e+05,
        3.5318381e+05],
       [0.0000000e+00, 1.0000000e+00, 2.0229590e+04, 6.5947930e+04,
        1.8526510e+05],
       [0.0000000e+00, 1.0000000e+00, 6.1136380e+04, 1.5270192e+05,
        8.8218230e+04],
       [1.0000000e+00, 0.0000000e+00, 7.3994560e+04, 1.2278275e+05,
        3.0331926e+05],
       [1.0000000e+00, 0.0000000e+00, 1.4210734e+05, 9.1391770e+04,
        3.6616842e+05]])

In [43]:
y_predict = regressor.predict(X_test)

In [44]:
y_predict

array([103015.20159796, 132582.27760816, 132447.73845175,  71976.09851259,
       178537.48221054, 116161.24230163,  67851.69209676,  98791.73374688,
       113969.43533012, 167921.0656955 ])

In [45]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [46]:
from sklearn import metrics

In [47]:
print(metrics.mean_absolute_error(y_test,y_predict))

7514.293659636814


In [49]:
print(metrics.mean_squared_error(y_test,y_predict))

83502864.03250548


In [50]:
print(np.sqrt(metrics.mean_squared_error(y_test,y_predict)))

9137.990152791011
