<a href="https://colab.research.google.com/github/parth1614/Machine_Learning/blob/main/SimpleLinear_Regression_with_CSV_File_InbuiltMethods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
from google.colab import files
uploaded = files.upload()

Saving AWCustomers.csv to AWCustomers.csv


In [4]:
dataframe = pd.read_csv("AWCustomers.csv")

In [5]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18361 entries, 0 to 18360
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   CustomerID            18361 non-null  int64 
 1   Title                 101 non-null    object
 2   FirstName             18361 non-null  object
 3   MiddleName            10572 non-null  object
 4   LastName              18361 non-null  object
 5   Suffix                3 non-null      object
 6   AddressLine1          18361 non-null  object
 7   AddressLine2          311 non-null    object
 8   City                  18361 non-null  object
 9   StateProvinceName     18361 non-null  object
 10  CountryRegionName     18361 non-null  object
 11  PostalCode            18361 non-null  object
 12  PhoneNumber           18361 non-null  object
 13  BirthDate             18361 non-null  object
 14  Education             18361 non-null  object
 15  Occupation            18361 non-null

In [6]:
#dataset = pd.read_csv('C:/Users/Susan/Desktop/Salary_Data.csv')
X = dataframe.iloc[:, :-1].values
y = dataframe.iloc[:, 1].values


In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)

In [9]:
X_train

array([[21058, nan, 'Meredith', ..., 0, 0, 36545],
       [29227, nan, 'Levi', ..., 0, 1, 106472],
       [29163, nan, 'Mason', ..., 0, 0, 81925],
       ...,
       [23260, nan, 'Edwin', ..., 2, 2, 33097],
       [21916, nan, 'Jesse', ..., 0, 2, 80254],
       [18995, nan, 'Melissa', ..., 0, 1, 78879]], dtype=object)

In [10]:
y_train

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [11]:
X_test

array([[23994, nan, 'Raymond', ..., 0, 0, 59075],
       [27750, nan, 'Carlos', ..., 0, 0, 109285],
       [16289, nan, 'Julie', ..., 0, 0, 53430],
       ...,
       [29316, nan, 'Max', ..., 0, 0, 84153],
       [29337, nan, 'Hector', ..., 0, 1, 61327],
       [24799, nan, 'Byron', ..., 0, 0, 112920]], dtype=object)

In [12]:
y_test

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)
##will work with correct dataset

In [ ]:
# Predicting the test set results
y_pred = regressor.predict(X_test)

In [ ]:
# Visualizing the training set
plt.scatter(X_train, y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary vs Experience (training set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

In [ ]:
# Visualizing the test set 
plt.scatter(X_test, y_test, color = 'red')
plt.plot(X_train, regressor.predict(X_train), color = 'blue')
plt.title('Salary vs Experience (test set)')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()